### ISSUE TITLE
WESTPA should require h5py>=2.10

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa#101]
Seems like right now you can get away with installing WESTPA while having h5py < 2.10. In 2.10, the `string_dtype` functions were added, which are used in some places of the WESTPA code. If you're running h5py < 2.10, you get a fairly opaque error.

Fix: Update WESTPA requirements to enforce `h5py>=2.10`. I think this should be part of the Conda package, but I honestly don't have firsthand experience with dependency management so if anyone else has better insight I'd love to know what the proper solution is!

**Comment by ltchong** [comment]
@burntyellow and @synapticarbors can you please look into this issue with the latest Conda package for WESTPA Python 3?

**Comment by synapticarbors** [comment]
In the latest version of `westpa` on conda-forge, the recipe requires that `h5py == 2.10.*`, so you shouldn't be able to pull in `h5py < 2.10`.  Two questions to clarify the issue:

1. Are you installing `westpa` into an existing conda environment, or are you creating one from scratch? Even in the former case, the `h5py` dependency should be forced to the correct version.

2. When did you try this and see the problem? Version `2.10` was a requirement as of https://github.com/conda-forge/westpa-feedstock/commit/fa585a7cec2cc75971a3942117debad8d95f5762, which was back on March 23rd.

**Comment by jdrusso** [comment]
Thanks for the response -- this came up helping someone else debug their environment, so I can't speak to the state of it. However, I do see that on a fresh install I just did it's pulled 2.10.0, so it's entirely possible this was all just due to an install from before that March 23 update.
