### ISSUE TITLE
Possibly apply Black to code

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#104]
A conversation on the developers list prompted me to suggest that at some point, we might consider applying the Black code formatter to westpa (https://black.readthedocs.io/en/stable/). Not everyone loves every aspect of the style it enforces, but on a project with multiple developers, consistency is often more important than smaller issues one might have with the formatting it produces. A few notes:

- Black is used on a number of large python projects including pandas and sqlalchemy (see https://github.com/psf/black#used-by)

- It does a consistency check between the AST from the parsed python code and the reformatted code, so it's just not blindly rewriting files.

- There aren't many config options, but the big ones would be the maximum line length and whether to enforce single or double quotes. While we're at it, we should probably decide on a linter and its configuration as well. My vote would be for `flake8` (https://flake8.pycqa.org/en/latest/). 

- We'd want to apply it to the entire code base and then enforce a way to make sure that we don't have subsequent commits that are fixing formatting. This is best done with CI on pull requests that apply Black and any other linters and give an error if the code needs additional formatting. Also individual developers would probably benefit from setting up pre-commit (https://pre-commit.com/)

**Comment by jeremyleung521** [comment]
Implemented in WESTPA 2.0. Closing.
