### ISSUE TITLE
Bug in work_manager core using non-type in `isinstance` call

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#107]
In `work_manager/core.py`, the following fails:

`isinstance(self._traceback, h5py.string_dtype(encoding='utf-8'))`

https://github.com/westpa/westpa/blob/master/lib/wwmgr/work_managers/core.py#L324

and can be simply reproduced with 

```
In [1]: import h5py

In [2]: isinstance('a', h5py.string_dtype(encoding='utf-8'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e1c0b8ba5993> in <module>
----> 1 isinstance('a', h5py.string_dtype(encoding='utf-8'))

TypeError: isinstance() arg 2 must be a type or tuple of types
```

This is because `h5py.string_dtype(encoding='utf-8')` is not a type, but a `dtype` object. The following will not throw an error, but I'm not sure if it's the correct thing to replace it with: `isinstance('a', h5py.string_dtype(encoding='utf-8').type)` or if it should just be `isinstance(self._traceback, str)`.

**Comment by atbogetti** [comment]
Josh, Everytime I have encountered this error, changing the problematic line to `isinstance('a', h5py.string_dtype(encoding='utf-8').type)` has worked for me.  Can we make this a permanent change in the code to eliminate this error for good?
