### ISSUE TITLE
HDF5 Framework

### ISSUE THREAD

**Issue by SHZ66** [westpa/westpa#138]
Hi All,

I would like to use this issue page to summarize and update on the points we discussed in the last dev meeting regarding the implementation of the new HDF5 framework. 

### Per-iteration HDF5 files (iter_00000001.h5): 
Separate HDF5 files will be generated after each iteration to store trajectories (segments), state/restart data, as well as the topology. Trajectories from different segments will be concatenated, and a pointer array will be stored to help separate them. 
- **times**, shape=(n_frames=n_segments × n_frames_per_segment).
- **coordinates**, shape=(n_frames, n_atoms, 3).
- **velocities**, shape=(n_frames, n_atoms, 3).
- **topology** (may be made optional if redundancy is a problem).
- [Optional] cell_lengths, cell_angles, kineticEnergy, potentialEnergy, temperature, lambda, constraints.
- **pointers**, shape=(n_frames, 2). Each entry would be the index of the iteration and the segment to which the corresponding frame belongs.
- **restart**, data read from .nc or .xml files and transformed to a unified data format (need to think about later). 

These files are perfectly compatible with MDTraj's HDF5 reader. Having HDF5 files separated by iterations is to minimize the damage caused by data corruption.

### Master HDF5 files (west.h5): 
In addition to data already stored in west.h5, links to per-iteration HDF5 files will be added among some other data:
- **/iterations/iter_00000001/trajectories -> iter_00000001.h5**, external links to per-iteration files. An example value of these links might be "traj_segs/iter_00000001.h5".
- **/iterations/iter_00000001/pcoord**, which is already in west.h5. But now we read it for indexing/selecting purposes.

A different reader than MDTraj's will need to be implemented in order to read this information and construct a whole trajectory object. The benefit of having this information in west.h5 is that the trajectory object will then have the access to `pcoord` without the need of reading another file, and therefore allows advanced indexing/selection based on bins. The downside of having these separate files is that when the files need to be organized in a certain way in order to be correctly read - the links can be broken if they do not exist.

### `class WESTTrajectory(mdtraj.Trajectory):`
- Fully compatible with MDTraj’s functions, e.g. `rmsds = md.rmsd(traj, traj, 0)`.
- More advanced indexing, i.e. `traj[:1000]` → `westtraj[:10, :50, :]` (first ten iterations; first 50 segments from each; all frames).
- This data structure can host data read from either a per-iteration or a master HDF5 file. In the former case, the number of iterations will simply be one.

### `class WESTIterationFile(mdtraj.HDF5TrajectoryFile):`
- Derived from `mdtraj.HDF5TrajectoryFile` – Use MDTraj’s infrastructure to save (and load) trajectory data.
- It can read/write data from/to per-iteration HDF5 files mentioned above, especially the pointers.
- Upon loading, it will create a `WESTTrajectory` object that has only one iteration.

### `class WESTTrajectoryFile(WESTIterationFile):`
- Derived from `WESTIterationFile` just so that we have access to the PyTables API through MDTraj (alternatively, we could use PyTables or h5py directly but WESTIterationFile uses MDTraj to interface with HDF5 already), and writer/reader needs to be completely rewritten for this one, as explained by the following bullet points.
- It can read links, bin_labels, and topology from the master HDF5 file mentioned above. It will automatically skip the links if they are broken for robustness.
- It can write/append data to the master HDF5 file so that data can be incremented as the simulation progresses.
- Upon loading, it will create a `WESTTrajectory` object that only has several iterations.

## Internal code changes
The h5 files serve as data storage and checkpoints:
- MD engines write data to a single (temporary) trajectory folder, instead of nested folders in *traj_segs*. 
- Save data generated by MD engines (.dcd, .nc, .xml, .rst) to *west.h5* after an iteration finishes using `WESTTrajectoryFile.write`.
- Restart from any per-iteration HDF5 file.
- `w_trace`, `w_ipa`, etc. 

Hopefully, this addresses some of the concerns raised in the meeting and summarized the key points. Please feel free the comment below any concerns or suggestions you have. I will keep the post updated as we go. 

Thanks,
She

**Comment by agrossfield** [comment]
I have a big-picture question: what problem is this file format supposed to solve? what is hard/problematic now that we're hoping to resolve by doing this?

I can think of a couple:

- make the data storage independent of the underlying MD engine
- reduce the number of small files created (only helps if you can make the MD engine do it directly)
- space efficiency (maybe, since I don't think HDF5 is compressed, so these files will be bigger than xtc and roughly the same size at dcd)
- reduce confusion about naming conventions, etc, since everything will be inside the hdf5 file and controlled by westpa

I think we need to be clear what these goals are first, so we can design the file format to solve those problems.

**Comment by SHZ66** [comment]
@agrossfield Thanks a lot for the questions, as well as the ones you raised during the meeting! 

I don't think I know WESTPA well enough to provide a complete answer to your question, but I will try to answer based on the project proposal that Lillian and Anthony forwarded to me. There are three main goals mentioned in that proposal, which are:

- Efficient storage of data from any type of simulation to facilitate the sharing of large datasets.
- Efficient analysis of large datasets using any suite of analysis tools.
- Simplified startup, restarting, and analysis of simulations.

The current implementation focuses on the first two as I am gonna need to read a bit more of WESTPA code to understand how this new framework will help simplify restarts. As you mentioned, HDF5 would provide data storage in a unified format, so that analysis tools for WESTPA trajectories can be implemented more easily. For example, in the tutorial, there is a bash command that uses cpptraj to concatenate relevant segments into one trajectory, but that may only work with certain file formats, e.g. Amber's nc files. After having data stored in the H5 files, we can implement and ship a tool within WESTPA that does that, regardless of how the trajectories are generated. There will be many other benefits on the analysis side, for example, slicing and manipulating the trajectory data more easily with MDTraj's or WESTPA's own APIs.

Regarding space efficiency, HDF5 does support compression and uses zlib by default, if I remember correctly. I can confirm that the file size is smaller than the sum of the sizes of data files being included. The number of small files created by the MD engine may be reduced too, in the way that we can clear up the "raw data" after they are no longer needed (i.e. when data is written to h5). In a more ideal case, MD engine will write data to the HDF5 file either directly, or through a media such as a RAM disk or [rasterio](https://rasterio.readthedocs.io/en/latest/topics/memory-files.html). 

I will keep thinking about other possible major goals we'd like to achieve by implementing the framework while waiting for others to chime in. I agree that it is crucial to think about these problems as early as possible to save us from more troubles later, which is also one of the purposes of having this post.

**Comment by agrossfield** [comment]
I’d stay away from messing with restarts. Not only do they require double precision velocities as well as positions (so 4x larger), they’re by definition specific to the MD engine.  The other goals make more sense to me.

**Comment by SHZ66** [comment]
@agrossfield This reminds me that I forgot to mention that we will now also put restart/state data (.rst or .xml) into the per-iteration h5 files. So when needed, we will export them from the h5 file to the simulation folder. Would that be a good way to address restarting?

**Comment by agrossfield** [comment]
You could, but at the point what’s the advantage — you’d have the md engine generate the restart file, import it into the hdf5 file and delete it, then re-export it when you want to use it. I don’t see why that’s easier than just keeping it around. It’s not like the trajectory data, which you’d want to manipulate for other reasons.

On Dec 14, 2020, at 4:11 PM, She Zhang <notifications@github.com> wrote:

﻿

@agrossfield<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_agrossfield&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=wC0yEQaafiQQ0zDie3JwWm9Onvk5Q5EXR0NbpQUcvR4&s=GxPhEnSWCo6hLpy_Qq_48bHtu6hZyfxRmi-88yAHySs&e=> This reminds me that I forgot to mention that we will now also put restart/state data (.rst or .xml) into the per-iteration h5 files. So when needed, we will export them from the h5 file to the simulation folder. Would that be a good way to address restarting?

**Comment by atbogetti** [comment]
I think the original intent was to have all the information required to restart a WESTPA simulation handy in the hdf5 file.  This would reduce the amount of errors from having files go missing or misplaced.  This wouldn't necessarily be a change for increased efficiency but it would allow for a fork of a WESTPA simulation where a user wouldn't have to copy over restart/trajectory data to begin that fork and instead would just need the h5 file, which would be more convenient.

**Comment by agrossfield** [comment]
Ok, that makes sense to me.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Dec 14, 2020, at 4:20 PM, Anthony Bogetti <notifications@github.com> wrote:

﻿

I think the original intent was to have all the information required to restart a WESTPA simulation handy in the hdf5 file. This would reduce the amount of errors from having files go missing or misplaced. This wouldn't necessarily be a change for increased efficiency but it would allow for a fork of a WESTPA simulation where a user wouldn't have to copy over restart/trajectory data to begin that fork and instead would just need the h5 file, which would be more convenient.

**Comment by jeremyleung521** [comment]
Implemented in #189 . Closing.
