### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by stefanv** [westpa/westpa#143]
I would like to verify that WESTPA is released under the MIT license.  That is what the LICENSE file says, but the README says it is GPL.

I tried to open a discussion from the [new issue page](https://github.com/westpa/westpa/issues/new/choose) but the bottom link there takes me to a page that says "Content Unavailable".

**Comment by ltchong** [comment]
Thank you for alerting us to the inconsistency in the README file -- this has been fixed. We recently switched from a GPL to MIT license for WESTPA.

**Comment by stefanv** [comment]
Excellent, thank you!
