### ISSUE TITLE
Discussion group inaccessible

### ISSUE THREAD

**Issue by stefanv** [westpa/westpa#144]
The [discussion group](https://groups.google.com/group/westpa-devel) advertised in the README is currently not accessible.

**Comment by synapticarbors** [comment]
That google group appears to be private since I can access it with the link using my email address. You likely just need an invite. There is also a slack channel for developers that's also active.

**Comment by synapticarbors** [comment]
@ltchong has control over both so she can probably send you an invite.

**Comment by stefanv** [comment]
It seems to have been opened now; thanks.
