### ISSUE TITLE
UnicodeDecodeError raised when attempting to run w_assign

### ISSUE THREAD

**Issue by castephens** [westpa/westpa#146]
Hello, 

I was attempting to run w_assign on my own WESTPA data set but the following error was raised:

  File "xxx/miniconda3/envs/westpa/westpa-2020.03/lib/west_tools/westtools/binning.py", line 74, in mapper_from_hdf5
    mapper = pickle.loads(pkldat) 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 3: ordinal not in range(128)

I was able to recreate this error using the .h5 file and west.cfg from the [intermediate_p53 tutorial](https://github.com/westpa/westpa_tutorials/tree/main/intermediate_p53). Here are the steps I took to do so:

1. made a fresh conda install of latest westpa version (WEST version 19.9.0) into a new environment with python 3.7 
2. copied the unzipped p53.h5 and west.cfg from the tutorial into a clean directory
3. ran the following within that directory:  `w_assign -W p53.h5`
4. This gave the exact same error above

Not sure it matters, but this was all run on a linux system.
I believe this may be related to the most recent issue on this page (#142)

**Comment by synapticarbors** [comment]
Thanks for the bug report. I'm wondering if that tutorial has been updated for python3. I don't think pickles created with python 2 are strictly compatible with python 3 due to differences in string encoding. 

Just to clarify, are you getting this error for both a simulation you ran as well as the p53 tutorial? If that's the case, was your data from your own WE run generated with an older version of WESTPA that pre-dates the python 3 transition?

**Comment by castephens** [comment]
Hello, 

Ah, so I used the same WESTPA version  (19.9.0) for my own simulation data. But, I just ran w_assign for the p53 tutorial data using an older WESTPA install (1.0.0 beta) and didn't get the pkl error, sorry about that. I would like to check a few things for my own simulations and get back to you.

**Comment by synapticarbors** [comment]
No problem. Don't hesitate to post any follow-up information about your own system if you continue to have problems and I or others can try help.

**Comment by castephens** [comment]
My apologies again, I forgot that I had made a customized pcoord_loader function is a system.py file to get WESTPA to accept a PC with length 1. I see now from an archived conversation that storing previous and current PC values is important for analysis and restarts. I may try to rebuild the h5 file with w_crawl to recover this data. 

To make sure my modification was causing the error I did the following:

1. Made a new clean run of my same simulation setup, but instead used the default pcoord_loader function and returned a PC of length 2. 
2. I ran for two iterations without any reported warnings or errors in my west.log file. 
3. Tried to run `w_assign -W west.h5` and encountered a new error:

File "xxx/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/binning.py", line 79, in mapper_from_hdf5
    raise KeyError('hash {} not found'.format(hashval))
KeyError: 'hash 008ca92a5f524acc6c762c3111eabede7f8a82e83c0490f9cd4fabc33ae4f0bb not found'

This was run using the latest WESTPA version available through conda (v19.9.0) with python 3.7.9 on a linux system.

**Comment by synapticarbors** [comment]
This sounds like it could be related to #142 (a quick glance at the code makes me think this is likely the issue).  Could you post the full traceback for the error you're getting and also your `system.py` if possible? 

@atbogetti -- I'm going to pull you in on this one since I think you have done a lot of testing of WESTPA workflows using the latest python3 release (I think this would be an issue for the stable release and the 2.0 dev branch). I'm thinking that `w_assign` must not be breaking under all circumstances since someone would have presumably noticed this before now.

**Comment by castephens** [comment]
thanks, sure thing:

Traceback (most recent call last):
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/w_assign.py", line 545, in <module>
    WAssign().main()
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/core.py", line 157, in main
    self.make_parser_and_process()
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/core.py", line 138, in make_parser_and_process
    self.process_all_args(args)
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/core.py", line 64, in process_all_args
    fn(self,args)
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/w_assign.py", line 274, in process_args
    self.binning.process_args(args)
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/binning.py", line 339, in process_args
    self.mapper, self.mapper_pickle, self.mapper_hash = mapper_from_hdf5(self.mapper_source_group, self.mapper_source_hash)
  File "/home/cstephens/miniconda3/envs/westpa_v19.9.0/westpa-2020.03/lib/west_tools/westtools/binning.py", line 79, in mapper_from_hdf5
    raise KeyError('hash {} not found'.format(hashval))
KeyError: 'hash 008ca92a5f524acc6c762c3111eabede7f8a82e83c0490f9cd4fabc33ae4f0bb not found'

**Comment by castephens** [comment]
Hey @atbogetti or @synapticarbors , any updates on this issue?

**Comment by atbogetti** [comment]
Hello, we are working hard to resolve this issue and will let you know as soon as we have a fix ready to go.  @jeremyleung521 is there a temporary fix for this in the meantime?

**Comment by jeremyleung521** [comment]
Hi @castephens,

Sorry for the long wait. If you would like to test out the [following repository](https://github.com/jeremyleung521/westpa/tree/hash-fix), it should fix the errors. If you prefer to wait, we will be merging these changes to WESTPA soon (hopefully these 2 weeks).
 
You can copy and paste the four fixed files in the your existing WESTPA installation. (Make copies so you can always revert the replacement)
- lib/west_tools/westtools/binning.py 
- src/west/data_manager.py 
- lib/west_tools/westpa/h5io.py 
- lib/west_tools/westtools/kinetics_tool.py 

Or you can consider reinstalling WESTPA after cloning the branch. 

Please let us know if you encounter any errors. 

-- JL
