### ISSUE TITLE
WESTPA versioning scheme

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#156]
Building off of the discussion in the developer's group meeting, it would be good to formalize a versioning scheme. Currently we use a variant of calendar versioning -> [calver](https://calver.org/). An alternative is sematic versioning -> [semver](https://semver.org/).

The issue with calver is a lack of clearly delineating major breaking changes. One way to deal with this is described in https://github.com/democritus-project/roadmap/issues/46. The general problem with semver is the need for discipline to actually meet the standard and make the scheme meaningful. 

Comments on how we should proceed would be appreciated.

**Comment by jeremyleung521** [comment]
Just in case anyone is interested in our current numbering system, [here](https://github.com/westpa/westpa/releases/tag/v2020.01)'s where that's documented. As far as I know, this is the only place with our change log/rationale on version numbers, so I feel like we should definitely publicize it more on the website too.

**Comment by dnlebard** [comment]
In my mind, semver is an easier to comprehend from a developers stance. From my experience, each "major" commit gets a patch bump or a minor release bump, and changes to the major version are infrequent and indicate a breaking change (for a developer, that change should be obvious). 

Both calver and semver versioning systems require discipline on some level -- either in the scheme for bumping for the major.minor.patch release numbers for semver, or in the documentation like calver. If we think we can be very disciplined in the documentation side, we could use calver. On the other hand, semver appears more natural from a developers perspective, but there is still ambiguity in what constitutes breaking vs. non-breaking changes and minor vs. patch changes. That said, I'm not really in favor of using the sem-cal-ver being used by the Democritus project either, and think for simplicity's sake we should stick with one of the popular versioning schemes.

**Comment by ltchong** [comment]
Sounds like there is a preference for using semver. Both @mczwier  and I are in favor of using semver for the reasons that @synapticarbors and @dnlebard have outlined. Having a versioning scheme that clearly delineates major breaking changes is important and we can be disciplined about using the scheme. If you have any concerns about going with semver, please speak up.

**Comment by mczwier** [comment]
I concur. We can nail down the specific details as we go, but a major/minor/patch versioning scheme (with the understanding that major version number updates can be expected to break things and patches should be expected to break nothing, with minor updates somewhere in the middle, perhaps only allowing minor changes at the API and storage schema levels) seems like a reasonable starting point.

**Comment by jeremyleung521** [comment]
We've established elsewhere (in the developers meetings) that we'll be going with 2022.XX/{MAJOR}.{MINOR} for the future releases. Major releases will be numbered by their release year, followed by the minor releases numbered from 01 onwards... This is consistent with the WESTPA 1.0 (e.g. 2020.05) numbering scheme. Closing this.
