### ISSUE TITLE
Complete Sphinx Documentation

### ISSUE THREAD

**Issue by KarlTDebiec** [westpa/westpa#16]
Hi all,
I'm starting this issue as a checklist of things that need or ought to be done for the sphinx documentation and corresponding GitHub pages site.
- [x] Update GitHub Pages site and link to sphinx documentation (@ASinanSaglam has this ready)
- [x] Modify sphinx Makefile to smoothly move docs to gh-pages branch
- [ ] Port appropriate parts of WESTPA wiki to sphinx
  - [x] NaCl tutorials
  - [ ] Update BioNetGen tutorial?
  - [x] Simulation checklist
  - [x] Alex's style guide
  - [ ] Workshop tutorials (where should the files for these go?)
  - [ ] Update outdated pages or replace them with stumps until they can be updated
  - [ ] Fix internal and external links
- [x] Port appropriate parts of WESTPA wiki to [GitHub's Wiki](https://github.com/westpa/westpa/wiki)
  - [x] Useful scripts
  - [x] FAQ
- [ ] Clean up and correct links and references in README.rst
- [ ] Follow Alex's style guide
- [ ] Document west extension usage
- [ ] Document code itself
- [ ] Implement consistent unified theme for Github Pages and sphinx (low priority)

**Comment by jeremyleung521** [comment]
Sphinx documentation has been implemented. Closing!
