### ISSUE TITLE
Pcoord Shape Error

### ISSUE THREAD

**Issue by jeremyleung521** [westpa/westpa#164]
## This is part of an initiative to improve error messages so end users can better know how to debug their simulations. 
To return to the hub, click on #163.

Sample Error:
Value Error: Progress coordinate data has incorrect shape {0,} [expected {20,}]

Relevant Code:
https://github.com/westpa/westpa/blob/main/src/west/propagators/executable.py#L42

Potential Causes:
- error in get_pcoord.sh and/or runseg.sh where data is not passed correctly
- data is literally the wrong shape so cannot be saved to pcoord (including wrong size specified in west.cfg as well as empty data)
- Walker propagation failed, so no data is passed/calculated.

Potential Fixes:

1.  #153 is a potential fix where the error message points to the relevant files (pcoord.err and seg_logs) to be debugged.

**Comment by jeremyleung521** [comment]
I think the current "potential fix" #153 has addressed it enough so the user knows where to look.

**Comment by wenchangzhou-qtx** [comment]
Hey @jeremyleung521, 

I'm still getting this error when I follow the westpa2_tutorial/tutorial-3.1, but adapt to my own system. I installed westpa2 a few weeks ago, I could repeat the tutorial-3.1 so it must be something wrong with my own system. Could you point me to where to check this type of error? Thanks.

**Comment by wenchangzhou-qtx** [comment]
In my case, I have one distance to sample, the error message is below.

```
Updating system with the options from the configuration file
Maximum wallclock time: 3 days, 0:00:00

Tue Mar 14 20:48:17 2023
Iteration 1 (100 requested)
Beginning iteration 1
35 segments remain in iteration 1 (35 total)
7 of 15 (46.666667%) active bins are populated
per-bin minimum non-zero probability:       0.1
per-bin maximum probability:                0.2
per-bin probability dynamic range (kT):     0.693147
per-segment minimum non-zero probability:   0.02
per-segment maximum non-zero probability:   0.04
per-segment probability dynamic range (kT): 0.693147
norm = 1, error in norm = 0 (0*epsilon)
MAB binning in use
Bottleneck bin occupancy may not be accurately reported
Waiting for segments to complete...
-- ERROR    [westpa.core.propagators.executable] -- could not read pcoord from '/tmp/tmpsl83mqjy': ValueError('cannot reshape array of size 6 into shape (3,1)')
......
```

**Comment by jeremyleung521** [comment]
Hi @wenchangzhou-qtx,

From the sounds of it, it's the changes you made in `runseg.sh` causing the problem. What you calculated (6) is not the right shape as what is expected (3, 1). I would double-check by printing out the datasets into stdout in `runseg.sh` and make sure the shape are of (3,1). Right now you have 6 numbers to fit in 3 spots.

This is probably not the best place to continue this conversation, but if you need more help, post in the mailing list (https://groups.google.com/g/westpa-users) and more of us will be able to help you.

-- JL
