### ISSUE TITLE
w_pdist ValueError: Value out of bin boundaries

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa#170]
## This is part of an initiative to improve error messages so end users can better know how to debug their simulations.

To return to the hub, click on #163.

### Sample Error:
```
Traceback (most recent call last):
  ....
  File "/Users/russojd/anaconda3/envs/westpa-2020/westpa-2020.03/lib/west_tools/w_pdist.py", line 53, in _remote_bin_iter
    histnd(dset[:,ipt,:], binbounds, weights, out=iter_hist, binbound_check = False, ignore_out_of_range=ignore_out_of_range)
  File "fasthist/_fasthist.pyx", line 39, in fasthist._fasthist.histnd
  File "fasthist/_fasthist.pyx", line 101, in fasthist._fasthist.histnd
  File "fasthist/_fasthist.pyx", line 226, in fasthist._fasthist._histnd
ValueError: value nan at index 194 out of bin boundaries in dimension 0
```

### Relevant code:
`w_pdist`

### Potential causes:
Walker blowing up

This simulation was run for 3841 iterations. I managed to bracket in the problematic iteration to iteration 2752 by tweaking `--first-iter and --last-iter`. Here, row 191 of `west.h5/iterations/iter_00002752` shows that after 4 steps, this particular walker blew up and started reporting an infinity and then `NaN`s. This walker continued to report NaNs in subsequent iterations.

### Potential fixes:
This error should more explicitly indicate that a walker has blown up.

However, this does raise some additional questions -- `w_fluxanl` ran with no complaints on this data, and WESTPA apparently encountered these `NaN`s and silently kept running. Seems like we should at least raise a warning in the output of every iteration if there's a blown-up walker.

**Comment by jdrusso** [comment]
After corresponding a bit with @atbogetti it seems like indeed, WESTPA checks for explicit failure (i.e. crashing outright) of the propagator, but not for sensible values of the progress coordinate.

I propose a simple check in the post-iteration for `NaN` or `inf` values. I'd love to hear thoughts on whether this would make more sense as a warning (one of your walkers has failed, proceed with caution) or an error (your dynamics are blowing up, fix it and start over)

**Comment by jeremyleung521** [comment]
Merged into HUB.
