### ISSUE TITLE
More informative error message when paths in west.cfg do not exist

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa#185]
## This is part of an initiative to improve error messages so end users can better know how to debug their simulations.

To return to the hub, click on #163.

### Sample Error:
```
System is being built only off of the system driver
Restart plugin initialized
Maximum wallclock time: 14 days, 0:00:00

Mon Aug  9 16:34:09 2021
Iteration 1 (250 requested)
Beginning iteration 1
4 segments remain in iteration 1 (4 total)
1 of 52 (1.923077%) active bins are populated
per-bin minimum non-zero probability:       1
per-bin maximum probability:                1
per-bin probability dynamic range (kT):     0
per-segment minimum non-zero probability:   0.25
per-segment maximum non-zero probability:   0.25
per-segment probability dynamic range (kT): 0
norm = 1, error in norm = 0 (0*epsilon)
exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/cli/core/w_run.py", line 62, in run_simulation
    sim_manager.run()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/core/sim_manager.py", line 695, in run
    self.propagate()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/core/sim_manager.py", line 540, in propagate
    incoming = future.get_result()
  File "/home/groups/ZuckermanLab/russojd/westpa/westpa/src/westpa/work_managers/core.py", line 334, in get_result
    raise self._exception.with_traceback(self._traceback)
TypeError: __traceback__ must be a traceback or None
```

### Potential causes:

When the paths provided in `west.cfg` don't exist, it can cause all sorts of arcane error messages that completely depend on the propagator. 

The above is an example of using the executable propagator w/ AMBER, when `seg_logs` and `traj_segs` don't exist. `w_init` even runs fine, but when you `w_run` you get the above.

### Potential fixes:

Ideally, a more meaningful traceback should get passed back (not sure why it doesn't get passed back up here). 

A really nice check would be making sure anything that's supposed to be a path in `west.cfg` is in fact a valid, existing path.

`self.segment_ref_template`, `self.basis_state_ref_template`, and `self.initial_state_ref_template` should be validated as paths whenever they're set in `westpa.rc`. Not sure where this happens

Similarly,  when loading in `stdout`/`stderr`/`stderr`/`cwd` at https://github.com/westpa/westpa/blob/westpa-2.0-restruct/src/westpa/core/propagators/executable.py#L142 we should use `yamlcfg.YAMLConfig.get_path` instead of `get`, which I think will handle validating the paths.

**Comment by jeremyleung521** [comment]
Merged into HUB.
