### ISSUE TITLE
Run object may exclude final iteration, and doesn't handle start states

### ISSUE THREAD

**Issue by jpthompson17** [westpa/westpa#225]
- I didn't catch this before, but it seems like Run excludes the last iteration by default. This will be difficult for people who `w_truncate`-ed to the desired length but can't access the last iteration.
- It won't load any trajectory with a `start_state` because it would hit an out of range error [here](https://github.com/westpa/westpa/pull/217/files#diff-fd81ae7e5f3026d581a5670d5faafefec44dcc35f5e317e0eee61e5a20f8e8beR308) since `basis_state_id > len of group(basis_state_id)`. Might be worth throwing an exception for `InitialState.ISTATE_TYPE_START` ([link](https://github.com/westpa/westpa/blob/westpa-2.0-restruct/src/westpa/core/states.py#L154)) now. It should be fixed once we have the fallback code to read from the bstates data ref files instead. 

Both can be checked with the west.h5 file in https://github.com/westpa/westpa2_tutorials/tree/main/basic_nacl/w_crawl
- iter 2 is not accessible.
- iter 1 walkers 15-19 are loadable, the rest can't because of the sstate issue. (Forseen problem in #222)

_Originally posted by @jeremyleung521 in https://github.com/westpa/westpa/issues/217#issuecomment-1018735223_

**Comment by jpthompson17** [comment]
Currently, the `num_iterations` attribute (or `__len__()` method) of a run returns `west_current_iteration - 1`. The idea was that the length of a run should be the number of *completed* iterations. The current logic works for west.h5 files where the last iteration is incomplete, e.g., https://github.com/westpa/westpa2_tutorials/blob/main/basic_nacl/for_analysis/nacl.hdf5.h5.1.tar.gz. However, it fails when the last iteration is complete, e.g., after running `w_truncate`.

I'm not sure what the best approach is for fixing this issue. My first thought is to inspect the last iteration group in the west.h5 file and check whether `(group['seg_index']['status'] == SEG_STATUS_COMPLETE).all()`. 

@jeremyleung521 Is there a better way to do this?

**Comment by jeremyleung521** [comment]
> Currently, the `num_iterations` attribute (or `__len__()` method) of a run returns `west_current_iteration - 1`. The idea was that the length of a run should be the number of _completed_ iterations. The current logic works for west.h5 files where the last iteration is incomplete, e.g., https://github.com/westpa/westpa2_tutorials/blob/main/basic_nacl/for_analysis/nacl.hdf5.h5.1.tar.gz. However, it fails when the last iteration is complete, e.g., after running `w_truncate`.
> 
> I'm not sure what the best approach is for fixing this issue. My first thought is to inspect the last iteration group in the west.h5 file and check whether `(group['seg_index']['status'] == SEG_STATUS_COMPLETE).all()`.
> 
> @jeremyleung521 Is there a better way to do this?

I think it would be better to use `west_current_iteration` if _any_ of the segments are complete (not all). It would cover the odd case where you would want to extract/view trajectories of a half-complete iteration (say, from system failure) and not lock the user out. Not sure if that'll introduce any extra problems, but if so, I'm ok with what you're suggesting.

**Comment by jeremyleung521** [comment]
Should be fixed with #226 and #227.
