### ISSUE TITLE
More specific error handling of failed auxdata returns

### ISSUE THREAD

**Issue by ajoshpratt** [westpa/westpa#25]
Currently, if the file containing the auxdata return value is empty, we simply pass along the empty contents down the data manager chain.

This ultimately fails during the h5 creation step, and a vague error is given:
"ValueError: All chunk dimensions must be positive (All chunk dimensions must be positive)"

This is likely because it's trying to initialize a dataset with a shape of 0, which isn't really a useful dataset, anyway.  We should check the shape of the data, ensure that it's larger than 1, and go on.  If not, we should throw a less vague error (IE, 'auxdata $i is of length 0'.)

**Comment by ajoshpratt** [comment]
Some shape/data checking is done in the data manager, around lines 1367 or so.  A quick line checking for the unique case of shape 0 should be sufficient.

**Comment by mczwier** [comment]
Sounds like a good idea to me.

**Comment by ajoshpratt** [comment]
I think it's better to just handle this in the following issue:
https://github.com/westpa/westpa/issues/26
