### ISSUE TITLE
Error in link.

### ISSUE THREAD

**Issue by rcrehuet** [westpa/westpa#308]
This is not an issue about WESTPA, but about the repository. The ink in the `https://github.com/westpa/westpa/wiki/Tutorials` file to "How to upgrade from WESTPA 1.0 to WESTPA 2.0" does not work.
The link "How to use the MAB scheme with WESTPA 2.0" does not work either.

**Comment by jeremyleung521** [comment]
Thank you for pointing that out! 

The videos were taken down because they are out of date but we forgot to remove them from the wiki. They are now off the wiki.

**Comment by jeremyleung521** [comment]
I also like to add that if users have any old simulations made using WESTPA 1.0 (v.2020.XX), you should continue to analyze them with any of the WESTPA 1.0 versions (v2020.06 is the newest one at the moment). We do recommend that any new simulations should be done on WESTPA 2.0 (v2022.XX).
