### ISSUE TITLE
String field issue in `basis_state_summaries` and `target_state_summaries`

### ISSUE THREAD

**Issue by jpthompson17** [westpa/westpa#417]
## Prerequisites
* [ ] Can you reproduce the problem in safe mode?
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

## Describe the bug

[This commit](https://github.com/westpa/westpa/commit/20ed02d595bacd90bb119c57fab655084ad2f248) appears to have introduced a bug in the `basis_state_summaries` and `target_state_summaries` attributes of `Iteration`, e.g.,
```
>>> run.iteration(1).target_state_summaries
                                               label
0  <pandas.core.strings.accessor.StringMethods ob...
```

Based on other changes included in that commit, it looks like maybe
```py
df[key] = df[key].decode('utf-8')
```
should have been changed to 
```py
df[key] = tostr(df[key])
```
instead of
```py
df[key] = tostr(df[key].str)
```

## To Reproduce

Open a west.h5 file as a `Run`, then access the basis state summaries for the first iteration:
```py
from westpa.analysis import Run
run = Run.open('west.h5')
print(run.iteration(1).basis_state_summaries)
```

**Comment by jeremyleung521** [comment]
Fixed in #418
