### ISSUE TITLE
w_init failing to save trajectory, restart, and log data to the per-iteration HDF5 file at iteration 0.

### ISSUE THREAD

**Issue by HScheiber** [westpa/westpa#456]
## Prerequisites
* [x] Can you reproduce the problem in safe mode?
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

## Describe the bug

When using per-iteration HDF5 files, I found that w_init will not properly generate the per-iteration HDF5 file for iteration 0 if using the processes work manager, but it will correctly produce the HDF5 file if using serial or threads work manager with a single worker.

## To Reproduce
Enable per-iteration HDF5 files, use the processes work manager, and use the following get_pcoord.sh for your simulation.

- pcoords.txt is just a pre-computed text file with the pcoords of the basis states
- seg.h5 is a trajectory file saved with mdtraj for your system of interest.
- seg.trr is a trajectory file containing just one frame (multiple frames will work as well), corresponding to the microstate of your basis state. This was generated using GROMACS, but I'm pretty sure this bug is data type agnostic.

```shell
#!/bin/bash
if [ -n "$SEG_DEBUG" ] ; then
  set -x
  env | sort
fi

# Return the progress coordinate value for this segment
cat $WEST_BSTATE_DATA_REF/pcoords.txt > $WEST_PCOORD_RETURN

# Now we save the solute trajectory into the HDF5 framework for storage
cp $WEST_BSTATE_DATA_REF/seg.h5 $WEST_TRAJECTORY_RETURN/seg.h5

# This is the only restart file actually needed by gromacs for the next iteration
# Note the seg.trr trajectory file is a full precision file with solute and solvent
# The seg.gro file is not needed as a common file is used for all segments
# An input seg.edr file is not read by gmx grompp unless using the Nose-Hoover thermostat 
# and/or Parinello-Rahman barostat
cp $WEST_BSTATE_DATA_REF/seg.trr $WEST_RESTART_RETURN/parent.trr
```

## Expected behavior
After running 
```shell
w_init $BSTATE_ARGS $TSTATE_ARGS --work-manager=processes --n-workers=48 "$@" >> west.log 2>&1
```
I would expect a per-iteration HDF5 file containing the trajectory and restart data for my basis states to be present in `$WEST_SIM_ROOT/trag_segs/iter_000000.h5`.

## Actual behavior
`$WEST_SIM_ROOT/trag_segs/iter_000000.h5` is created by w_init, but it is empty

## WESTPA version and platform
2022.11

## Additional context
I Found the bug, it is caused by westpa.core.sim_manager.get_bstate_pcoords. Currently, the function is
```python
def get_bstate_pcoords(self, basis_states, label='basis'):
    '''For each of the given ``basis_states``, calculate progress coordinate values
    as necessary.  The HDF5 file is not updated.'''

    self.rc.pstatus('Calculating progress coordinate values for {} states.'.format(label))
    futures = [self.work_manager.submit(wm_ops.get_pcoord, args=(basis_state,)) for basis_state in basis_states]
    fmap = {future: i for (i, future) in enumerate(futures)}
    for future in self.work_manager.as_completed(futures):
        basis_states[fmap[future]].pcoord = future.get_result().pcoord
```
The issue is in the final line. Basis state **pcoords and data** are grabbed by the `wm_ops.get_pcoord` function, and they update the basis states present in `futures`. However, only the **pcoord** is actually copied back with `future.get_result().pcoord`. When using serial or threads work manager (with 1 thread), the actual instantiation of basis states are passed into the work manager and updated in-place (so `basis_states[fmap[future]].pcoord = future.get_result().pcoord` just copies data from itself into itself). When using the **processes** work manager, the basis state objects are **copied**, then pcoord and data are injected into them, and then they are returned. Only the pcoords get copied back by `basis_states[fmap[future]].pcoord = future.get_result().pcoord`. A fix for this bug is to simply assign the entire basis state object to the `basis_states` list, like so:

```python
def get_bstate_pcoords(self, basis_states, label='basis'):
    '''For each of the given ``basis_states``, calculate progress coordinate and data values
    as necessary.  The HDF5 file is not updated.'''

    self.rc.pstatus('Calculating progress coordinate values for {} states.'.format(label))
    futures = [self.work_manager.submit(wm_ops.get_pcoord, args=(basis_state,)) for basis_state in basis_states]
    fmap = {future: i for (i, future) in enumerate(futures)}
    for future in self.work_manager.as_completed(futures):
        basis_states[fmap[future]] = future.get_result()
```

**Comment by HScheiber** [comment]
Note I previously reported this bug in the [WESTPA mailing list, here.](https://groups.google.com/g/westpa-users/c/mQD_8YGtDQs/m/wRlEmbUFAQAJ) I should note that my solution allows the user to use processes work manager with w_init again, but it does not fix the threads work manager crashing when using more than 1 thread. That seems to be a low-level HDF5 issue.

**Comment by jeremyleung521** [comment]
Thanks for catching this @HScheiber! (and sorry for missing your bug report from the mailing list.) I just created #457 with the fix you proposed.

**Comment by HScheiber** [comment]
Thanks Jeremy! Congrats on defending your PhD thesis!
