### ISSUE TITLE
`max_run_wallclock` not converted properly depending on format

### ISSUE THREAD

**Issue by synapticarbors** [westpa/westpa#5]
_Migrated from Redmine issue tracker_

Author: @synapticarbors
Date: 8/17/2013

Description

When the configuration parser reads the `max_run_wallclock` time from west.cfg, it is sensitive to the format. For example `max_run_wallclock: 3:00:00` works, but `max_run_wallclock: 03:00:00` gives an error like:

``` python
exception caught; shutting down
-- ERROR [w_run] -- Traceback (most recent call last):
File "/work/01633/tg809245/westpa/lib/cmds/w_run.py", line 65, in <module>
sim_manager.run()
File "/work/01633/tg809245/westpa/src/west/sim_manager.py", line 617, in run
run_killtime = run_starttime + max_walltime
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

since it is just being pass through as a string, rather than being converted to seconds. Likewise, if you are running for less than an hour, you must set the variable to mm:ss rather than 00:mm:ss.

This is fragile and the code should probably do some explicit check/conversion

**Comment by jeremyleung521** [comment]
#413 Dealt with this.
