### ISSUE TITLE
Make setup.sh capable of building tarballs

### ISSUE THREAD

**Issue by mczwier** [westpa/westpa#7]
To put tarballs up on Github, it would be helpful for our setup script to be able to retrieve the required supporting packages (blessings, west_tools, wwmgr) and build the tarballs while excluding .git directories. The natural place to do this is in setup.sh, since that's where the package retrieval occurs.
As this change is made, It might be beneficial to consider moving setup.sh into a Python script for greater compatibility and flexibility.

**Comment by jeremyleung521** [comment]
Current installation on conda takes care of this and WESTPA2.0 will include more installation methods that will take care of this (ie. python setup.py or pip install). Closing!
