### ISSUE TITLE
Remove TrajWriter function from all tutorials/examples

### ISSUE THREAD

**Issue by astatide** [westpa/westpa#82]
Currently, the examples shipped with WESTPA include a "TrajWriter" function, which uses some bash/sed magic to place Na/Cl coordinates into the main HDF5 file.  The purpose was to make this easier to visualize the trajectories from the examples.

However, the function is currently broken.  In addition, it's almost certainly not appropriate for general use, as writing coordinates is expensive, size wise, and will result in unwieldy HDF5 files for large production systems.  It is also not a core part of WESTPA, so supporting it requires development time that would be better spent on _actually_ handling trajectory data in a proper, general way.

We should remove the function and update the tutorials/examples with scripts/methods to properly handle trajectory visualization for each dynamics package.

**Comment by jeremyleung521** [comment]
With the introduction of the HDF5 framework (and to certain extent the haMSM plugin) for WESTPA2.0, I believe this is no longer necessary/relevant.
